server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    bus:
      enabled: true
      trace:
        enabled: true
    config:
      server:
        git:
          uri: https://github.com/Jere-ling/springcloud-config.git
          search-paths:
            - springcloud-config
          skip-ssl-validation: true
      label: master
  #rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'
